# Generated by Django 5.1 on 2024-09-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='service_time',
        ),
        migrations.AddField(
            model_name='patient',
            name='condition_severity',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='expected_service_time',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='queue',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
