# Generated by Django 5.1 on 2024-09-05 11:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0002_remove_queue_service_time_patient_condition_severity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='arrival_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
